# Generated by Django 4.0.4 on 2022-12-17 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField()),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('', 'Seleccione...'), ('RESERVADO', 'Reservado'), ('COMPLETADO', 'Completado'), ('ANULADA', 'Anulada'), ('NO ASISTEN', 'No asisten')], max_length=10)),
                ('observacion', models.CharField(blank=True, max_length=100)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serialApp.institucion')),
            ],
        ),
    ]
